# FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel
FROM pipeswitch:base

WORKDIR /workspace

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install matplotlib
RUN pip install transformers==2.5.0

WORKDIR /workspace

COPY . /workspace

ENV PYTHONPATH=/workspace

WORKDIR /workspace

RUN python scripts/environment/container_download_models.py

WORKDIR /workspace