FROM pipeswitch:base

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install matplotlib
RUN pip install transformers==2.5.0

WORKDIR /workspace

COPY . /workspace

ENV PYTHONPATH=/workspace

WORKDIR /workspace
RUN python scripts/environment/container_download_models.py

WORKDIR /workspace/mps
RUN bash overwrite.sh /workspace/pytorch/

WORKDIR /workspace/pytorch
ENV CMAKE_PREFIX_PATH=/opt/conda/
RUN python setup.py install

WORKDIR /workspace