# FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel
FROM pipeswitch:base

WORKDIR /workspace

# RUN apt-get update && apt-get install -y git

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install matplotlib
RUN pip install transformers==2.5.0
RUN mkdir -p /root/.cache/torch/hub/refs/tags && chmod -R 777 /root/.cache/torch/hub/refs/tags

WORKDIR /workspace
# RUN git clone --branch dev https://github.com/baizh1994/PipeSwitch.git
RUN git clone --branch main https://github.com/eamonmahon/PipeSwitch.git


ENV PYTHONPATH=/workspace/PipeSwitch

WORKDIR /workspace/PipeSwitch

RUN python scripts/environment/container_download_models.py

WORKDIR /workspace
RUN rm -rf PipeSwitch

WORKDIR /workspace