FROM pipeswitch:base

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install matplotlib
RUN pip install transformers==2.5.0
RUN mkdir -p /root/.cache/torch/hub/refs/tags && chmod -R 777 /root/.cache/torch/hub/refs/tags

WORKDIR /workspace
RUN git clone --branch main https://github.com/eamonmahon/PipeSwitch.git

ENV PYTHONPATH=/workspace/PipeSwitch

WORKDIR /workspace/PipeSwitch
RUN python scripts/environment/container_download_models.py

WORKDIR /workspace/PipeSwitch/pytorch_plugin
RUN bash overwrite.sh /workspace/pytorch/

WORKDIR /workspace/pytorch
ENV CMAKE_PREFIX_PATH=/opt/conda/
RUN python setup.py install

WORKDIR /workspace
RUN rm -rf PipeSwitch

WORKDIR /workspace